### DISCUSSION TITLE
What's a valid pyproject.toml file to build from inboard images?

### DISCUSSION THREAD

**Discussion by diegoquintanav** [br3ndonland/inboard#53] [Q&A] [answered]
Thanks again!

As stated in the [docs](https://inboard.bws.bio/docker), I could build my own image, based from inboards image

```
FROM ghcr.io/br3ndonland/inboard:fastapi

# Install Python requirements
COPY poetry.lock pyproject.toml /app/
WORKDIR /app
RUN poetry install --no-dev --no-interaction --no-root

# Install Python app
COPY package /app/package
ENV APP_MODULE=package.main:app
# RUN command already included in base image
```

Starting from a default repository (`poetry new package`) with this structure

```
.
└── package
    ├── Dockerfile
    ├── package
    │   └── __init__.py
    ├── pyproject.toml
    ├── README.rst
    └── tests
        ├── __init__.py
        └── test_package.py

3 directories, 6 files
```

with a default `pyproject.toml`

```toml
[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["Diego Quintana <daquintanav@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
flake8 = "^4.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

a first build _removes_ fastapi dependencies. If I add `inboard = {version = "^0.26.0", extras = ["fastapi"]}` to the toml file then I get 

```
Step 4/6 : RUN poetry install --no-dev --no-interaction --no-root
 ---> Running in b0dd25271364
Installing dependencies from lock file
Warning: The lock file is not up to date with the latest changes in pyproject.toml. You may be getting outdated dependencies. Run update to update them.

  SolverProblemError

  Because package depends on inboard (^0.26.0) which doesn't match any versions, version solving failed.
```

What's an example of a pyproject.toml file used in the documented example? Thanks again!
